//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Budford.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Budford.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon cemu {
            get {
                object obj = ResourceManager.GetObject("cemu", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest version is already installed.
        /// </summary>
        internal static string CemuFeatures_DownloadLatestGraphicPack_Latest_version_is_already_installed {
            get {
                return ResourceManager.GetString("CemuFeatures_DownloadLatestGraphicPack_Latest_version_is_already_installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information....
        /// </summary>
        internal static string CemuFeatures_DownloadLatestVersion_Information___ {
            get {
                return ResourceManager.GetString("CemuFeatures_DownloadLatestVersion_Information___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The latest version of Cemu is already installed..
        /// </summary>
        internal static string CemuFeatures_DownloadLatestVersion_The_latest_version_of_Cemu_is_already_installed_ {
            get {
                return ResourceManager.GetString("CemuFeatures_DownloadLatestVersion_The_latest_version_of_Cemu_is_already_installe" +
                        "d_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eu_flag {
            get {
                object obj = ResourceManager.GetObject("eu_flag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name exists!.
        /// </summary>
        internal static string fEditInstalledVersion_button4_Click_Name_exists_ {
            get {
                return ResourceManager.GetString("fEditInstalledVersion_button4_Click_Name_exists_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select another name before continuing.
        /// </summary>
        internal static string fEditInstalledVersion_button4_Click_Please_select_another_name_before_continuing {
            get {
                return ResourceManager.GetString("fEditInstalledVersion_button4_Click_Please_select_another_name_before_continuing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        internal static string fFileDownload_fFileDownload____ {
            get {
                return ResourceManager.GetString("fFileDownload_fFileDownload____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading .
        /// </summary>
        internal static string fFileDownload_fFileDownload_Downloading_ {
            get {
                return ResourceManager.GetString("fFileDownload_fFileDownload_Downloading_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is corrupted.
        /// </summary>
        internal static string FileCache_fileCache_openExisting___0___is_corrupted {
            get {
                return ResourceManager.GetString("FileCache_fileCache_openExisting___0___is_corrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Click on OK to continue.
        /// </summary>
        internal static string FileManager_ImportShaderCache_ {
            get {
                return ResourceManager.GetString("FileManager_ImportShaderCache_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About to import shader cache for .
        /// </summary>
        internal static string FileManager_ImportShaderCache_About_to_import_shader_cache_for_ {
            get {
                return ResourceManager.GetString("FileManager_ImportShaderCache_About_to_import_shader_cache_for_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string FileManager_ImportShaderCache_Continue {
            get {
                return ResourceManager.GetString("FileManager_ImportShaderCache_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder doesn&apos;t exist: .
        /// </summary>
        internal static string FileManager_SearchForInstalledVersions_Folder_doesn_t_exist__ {
            get {
                return ResourceManager.GetString("FileManager_SearchForInstalledVersions_Folder_doesn_t_exist__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveDirs saved successfully.
        /// </summary>
        internal static string fMainWindow_dumpSaveDirCodesToolStripMenuItem_Click_SaveDirs_saved_successfully {
            get {
                return ResourceManager.GetString("fMainWindow_dumpSaveDirCodesToolStripMenuItem_Click_SaveDirs_saved_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string fMainWindow_dumpSaveDirCodesToolStripMenuItem_Click_Success {
            get {
                return ResourceManager.GetString("fMainWindow_dumpSaveDirCodesToolStripMenuItem_Click_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budford - Cemu Configuration Manager      Current User: .
        /// </summary>
        internal static string fMainWindow_fMainWindow_CEMU_Game_DB______Current_User__ {
            get {
                return ResourceManager.GetString("fMainWindow_fMainWindow_CEMU_Game_DB______Current_User__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shader Cache Files | *.bin;.
        /// </summary>
        internal static string fMainWindow_importShaderCacheToolStripMenuItem_Click_Shader_Cache_Files_____bin_ {
            get {
                return ResourceManager.GetString("fMainWindow_importShaderCacheToolStripMenuItem_Click_Shader_Cache_Files_____bin_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save folder doesn&apos;t exist.
        ///
        ///Perhaps the game hasn&apos;t been played yet....
        /// </summary>
        internal static string fMainWindow_openSaveFileLocationToolStripMenuItem_Click_ {
            get {
                return ResourceManager.GetString("fMainWindow_openSaveFileLocationToolStripMenuItem_Click_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder not found.
        /// </summary>
        internal static string fMainWindow_openSaveFileLocationToolStripMenuItem_Click_Folder_not_found {
            get {
                return ResourceManager.GetString("fMainWindow_openSaveFileLocationToolStripMenuItem_Click_Folder_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nintendo Launch Files | *.rpx;.
        /// </summary>
        internal static string fMainWindow_toolStripButton1_Click_Nintendo_Launch_Files_____rpx_ {
            get {
                return ResourceManager.GetString("fMainWindow_toolStripButton1_Click_Nintendo_Launch_Files_____rpx_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V.
        /// </summary>
        internal static string FormAbout_FormAbout_V {
            get {
                return ResourceManager.GetString("FormAbout_FormAbout_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphic Packs| *.zip;.
        /// </summary>
        internal static string FormEditInstalledVersions_importGraphicsPackToolStripMenuItem_Click_Graphic_Packs____zip_ {
            get {
                return ResourceManager.GetString("FormEditInstalledVersions_importGraphicsPackToolStripMenuItem_Click_Graphic_Packs" +
                        "____zip_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        internal static string FormMainWindow_mi_Click_Hello {
            get {
                return ResourceManager.GetString("FormMainWindow_mi_Click_Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently showing .
        /// </summary>
        internal static string FormMainWindow_PopulateListView_Currently_showing_ {
            get {
                return ResourceManager.GetString("FormMainWindow_PopulateListView_Currently_showing_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                  .
        /// </summary>
        internal static string FormMainWindow_RefreshList__________________ {
            get {
                return ResourceManager.GetString("FormMainWindow_RefreshList__________________", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launching .
        /// </summary>
        internal static string FormMainWindow_snapshotsToolStripMenuItem_Click_Launching_ {
            get {
                return ResourceManager.GetString("FormMainWindow_snapshotsToolStripMenuItem_Click_Launching_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shader Cache Files| *.bin;.
        /// </summary>
        internal static string FormShaderMerger_openToolStripMenuItem_Click_Shader_Cache_Files____bin_ {
            get {
                return ResourceManager.GetString("FormShaderMerger_openToolStripMenuItem_Click_Shader_Cache_Files____bin_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shader Cache Files| *.bin;.
        /// </summary>
        internal static string FormShaderMerger_saveAsToolStripMenuItem_Click_Shader_Cache_Files____bin_ {
            get {
                return ResourceManager.GetString("FormShaderMerger_saveAsToolStripMenuItem_Click_Shader_Cache_Files____bin_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  new shaders.
        /// </summary>
        internal static string FormShaderMerger_UpdateListView__new_shaders {
            get {
                return ResourceManager.GetString("FormShaderMerger_UpdateListView__new_shaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added .
        /// </summary>
        internal static string FormShaderMerger_UpdateListView_Added_ {
            get {
                return ResourceManager.GetString("FormShaderMerger_UpdateListView_Added_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ....
        /// </summary>
        internal static string fScanRomFolder_fScanRomFolder_____ {
            get {
                return ResourceManager.GetString("fScanRomFolder_fScanRomFolder_____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning .
        /// </summary>
        internal static string fScanRomFolder_fScanRomFolder_Scanning_ {
            get {
                return ResourceManager.GetString("fScanRomFolder_fScanRomFolder_Scanning_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        internal static string fWebpageDownload_fWebpageDownload____ {
            get {
                return ResourceManager.GetString("fWebpageDownload_fWebpageDownload____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading .
        /// </summary>
        internal static string fWebpageDownload_fWebpageDownload_Downloading_ {
            get {
                return ResourceManager.GetString("fWebpageDownload_fWebpageDownload_Downloading_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not find file.
        /// </summary>
        internal static string Launcher_LaunchCemu_Can_not_find_file {
            get {
                return ResourceManager.GetString("Launcher_LaunchCemu_Can_not_find_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cemu is not installed.
        /// </summary>
        internal static string Launcher_LaunchCemu_CEMU_is_not_installed {
            get {
                return ResourceManager.GetString("Launcher_LaunchCemu_CEMU_is_not_installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are using a removable storage device check it is plugged in and try again.
        /// </summary>
        internal static string Launcher_LaunchCemu_If_you_are_using_a_removable_storage_device_check_it_is_plugged_in_and_try_again {
            get {
                return ResourceManager.GetString("Launcher_LaunchCemu_If_you_are_using_a_removable_storage_device_check_it_is_plugg" +
                        "ed_in_and_try_again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please install Cemu.
        /// </summary>
        internal static string Launcher_LaunchCemu_Please_install_CEMU {
            get {
                return ResourceManager.GetString("Launcher_LaunchCemu_Please_install_CEMU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap oz_flag {
            get {
                object obj = ResourceManager.GetObject("oz_flag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  has already been installed.
        /// </summary>
        internal static string Unpacker_DownloadAndUnpack__has_already_been_installed {
            get {
                return ResourceManager.GetString("Unpacker_DownloadAndUnpack__has_already_been_installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string Unpacker_DownloadAndUnpack_Info {
            get {
                return ResourceManager.GetString("Unpacker_DownloadAndUnpack_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The latest version of .
        /// </summary>
        internal static string Unpacker_DownloadAndUnpack_The_latest_version_of_ {
            get {
                return ResourceManager.GetString("Unpacker_DownloadAndUnpack_The_latest_version_of_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap us_flag {
            get {
                object obj = ResourceManager.GetObject("us_flag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon wii_u {
            get {
                object obj = ResourceManager.GetObject("wii_u", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual C++ 2005 Redistributable is installed..
        /// </summary>
        internal static string WindowsOs_IsVc2005RedistInstalled_Visual_C___2005_Redistributable_is_installed_ {
            get {
                return ResourceManager.GetString("WindowsOs_IsVc2005RedistInstalled_Visual_C___2005_Redistributable_is_installed_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual C++ 2005 Redistributable is not installed..
        /// </summary>
        internal static string WindowsOs_IsVc2005RedistInstalled_Visual_C___2005_Redistributable_is_not_installed_ {
            get {
                return ResourceManager.GetString("WindowsOs_IsVc2005RedistInstalled_Visual_C___2005_Redistributable_is_not_installe" +
                        "d_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual C++ 2008 Redistributable is installed..
        /// </summary>
        internal static string WindowsOs_IsVc2008RedistInstalled_Visual_C___2008_Redistributable_is_installed_ {
            get {
                return ResourceManager.GetString("WindowsOs_IsVc2008RedistInstalled_Visual_C___2008_Redistributable_is_installed_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual C++ 2008 Redistributable is not installed..
        /// </summary>
        internal static string WindowsOs_IsVc2008RedistInstalled_Visual_C___2008_Redistributable_is_not_installed_ {
            get {
                return ResourceManager.GetString("WindowsOs_IsVc2008RedistInstalled_Visual_C___2008_Redistributable_is_not_installe" +
                        "d_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual C++ 2010 Redistributable is installed..
        /// </summary>
        internal static string WindowsOs_IsVc2010RedistInstalled_Visual_C___2010_Redistributable_is_installed_ {
            get {
                return ResourceManager.GetString("WindowsOs_IsVc2010RedistInstalled_Visual_C___2010_Redistributable_is_installed_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual C++ 2010 Redistributable is not installed..
        /// </summary>
        internal static string WindowsOs_IsVc2010RedistInstalled_Visual_C___2010_Redistributable_is_not_installed_ {
            get {
                return ResourceManager.GetString("WindowsOs_IsVc2010RedistInstalled_Visual_C___2010_Redistributable_is_not_installe" +
                        "d_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual C++ 2012 Redistributable is installed..
        /// </summary>
        internal static string WindowsOs_IsVc2012RedistInstalled_Visual_C___2012_Redistributable_is_installed_ {
            get {
                return ResourceManager.GetString("WindowsOs_IsVc2012RedistInstalled_Visual_C___2012_Redistributable_is_installed_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual C++ 2012 Redistributable is not installed..
        /// </summary>
        internal static string WindowsOs_IsVc2012RedistInstalled_Visual_C___2012_Redistributable_is_not_installed_ {
            get {
                return ResourceManager.GetString("WindowsOs_IsVc2012RedistInstalled_Visual_C___2012_Redistributable_is_not_installe" +
                        "d_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual C++ 2013 Redistributable is installed..
        /// </summary>
        internal static string WindowsOS_IsVC2013RedistInstalled_Visual_C___2013_Redistributable_is_installed_ {
            get {
                return ResourceManager.GetString("WindowsOS_IsVC2013RedistInstalled_Visual_C___2013_Redistributable_is_installed_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual C++ 2013 Redistributable is not installed..
        /// </summary>
        internal static string WindowsOs_IsVc2013RedistInstalled_Visual_C___2013_Redistributable_is_not_installed_ {
            get {
                return ResourceManager.GetString("WindowsOs_IsVc2013RedistInstalled_Visual_C___2013_Redistributable_is_not_installe" +
                        "d_", resourceCulture);
            }
        }
    }
}
